config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get '/maps', to: 'maps#index'

  resource :products

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :products do
    resources :pictures
  end

  get :search, controller: :pages


get '/catalogue', to: 'products#index'
get '/category/:id', to: 'products#showcategory', as: :category
get '/carts/checkout', to: 'carts#checkout'
resources :users, only: [:show]
resources :stores, only: [:create, :new, :show]
resource :store, only: [:edit, :update]
resource :cart, only: [:show]
resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
get '/products/:id/deactivate', to: 'products#deactivate'
get '/products/:id/activate', to: 'products#activate'
get '/transactions/checkout', to: 'transaction#checkout'
get '/transactions/execute', to: 'transaction#finish'
get '/user/receipt', to: 'users#receipt'
get '/store/history', to: 'stores#history'
get '/user/history', to: 'users#history'
post '/store/history/execute', to: 'stores#execute'
post '/user/history/execute', to: 'users#execute'

get '/redirect', to: 'stores#redirect', as: 'redirect'
get '/calendarcallback', to: 'stores#callback', as: 'callback'
get '/stores/:id/calendars', to: 'stores#calendars', as: 'calendars'
get '/events/:calendar_id', to: 'stores#events', as: 'events', calendar_id: /[^\/]+/
post '/events/:calendar_id', to: 'stores#new_event', as: 'new_event', calendar_id: /[^\/]+/
get '/user/delete', to: 'users#delete'

  match "404", :to => "pages#not_found", :via => :all
  match "500", :to => "pages#internal_server_error", :via => :all
end

app/models/store.rb
class Store < ApplicationRecord
	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

	def new
		if current_user.stores_id?
			redirect_to store_path(current_user.stores_id)
		end
	end

	def create
		@stores = Store.new(add_store_params)
		if @stores.save
			User.update(current_user.id, :stores_id => @stores.id)
			redirect_to root_path
		end

	end


	def show
		@store = Store.find(params[:id])
		@store_products = Product.active.where(stores_id: @store.id).all
		@store_inactive = Product.inactive.where(stores_id: @store.id).all
		@check = session[:authorization]

		@categories = Category.all
		@categoryDict = {'Furniture'=>0, 'Fashion'=>0, 'Office & Stationary'=>0, 'Foods & Drinks'=>0, 'Kitchen Tools'=>0, 'Tools'=>0, 'Automative'=>0, 'Hobby'=>0}

		for i in 0..(@categoryDict.count-1)
			title = @categories.find(i+1).title
			@categoryDict[title] = @store_products.where(categories_id: i+1).count
		end
	end


	def edit
    	@stores = Store.find_by(id:current_user.stores_id)
	end

	def update
    	@stores = Store.find_by(id:current_user.stores_id)
    	if @stores.update(stores_params)
    		redirect_to @stores
    	end
	end

	def history
		@store = Store.find(current_user.stores_id)
		@transaction = Transaction.where(stores_id: current_user.stores_id).all.order('id DESC')
		@month = []
		@monthDict = {1 =>'January', 2 =>'February', 3 =>'March', 4 =>'April', 5 =>'May', 6 =>'June', 7 =>'July', 8 =>'August', 9 =>'September', 10 =>'October', 11 =>'November', 12 =>'December'}
		for i in 0..12
			@month << @transaction.where('extract(month from created_at) = ?', i+1)
		end
	end

	def execute
		@order = Order.find(params[:order_id])
		@item = @order.order_items.find_by(product_id: params[:product])
		@transaction = Transaction.find_by(order_id: params[:order_id])

		@item.update!(status: "Shipped")
		@transaction.update!(status: "Shipped")
		redirect_to store_history_path
	end

	def redirect
    client = Signet::OAuth2::Client.new(client_options)

    redirect_to client.authorization_uri.to_s
  end

	def callback
    client = Signet::OAuth2::Client.new(client_options)
		client.update!(session[:authorization])
    client.code = params[:code]

    response = client.fetch_access_token!

    session[:authorization] = response

    redirect_to calendars_path(current_user.stores_id)
  end

	def calendars
		@store = Store.find(params[:id])
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @calendar_list = service.list_calendar_lists
  rescue Google::Apis::AuthorizationError
    response = client.refresh!

    session[:authorization] = session[:authorization].merge(response)

    retry
  end

	def events
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

    @event_list = service.list_events(params[:calendar_id])
  end

	def new_event
    client = Signet::OAuth2::Client.new(client_options)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client

		cal_name = params[:event][:name]
		cal_date = params[:event][:date].to_date

    today = Date.today

    event = Google::Apis::CalendarV3::Event.new({
      start: Google::Apis::CalendarV3::EventDateTime.new(date: cal_date),
			end: Google::Apis::CalendarV3::EventDateTime.new(date: cal_date + 1),
      summary: cal_name
    })

    service.insert_event(params[:calendar_id], event)

		redirect_to calendars_path(current_user.stores_id), :notice => "Successfully create event"
  end

  private

  def client_options
    {
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: 'https://go-market.herokuapp.com/calendarcallback'
    }
  end

	private

		def stores_params
			params.require(:store).permit(:name, :description, :avatar)
		end

		def add_store_params
			params.require(:stores).permit(:name, :description, :avatar)
		end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/calendars.html.erb
<% content_for :title, "Calendar - " %>

<div class="row" style="margin-top:5%; margin-bottom: 3%">
	<div class="col-md-3">
		<div class="row">
			<div class="col-md-12" id="seller-card">
				<div id="st-info">
					Seller Information
				</div>


				<div id="st-storeinfo">
					<% if @store.avatar? %>
				      <%= image_tag(@store.avatar.url, :class => "profile-picture") %>
				    <% else %>
					<%= image_tag( "products/p-camera.png", id: 'seller-card-picture', alt: 'store picture', style: "display: inline;", class: "img-frame") %>
				    <% end %>
					<div id="store-information">
						<p id="store-name"><%= @store.name.upcase %></p>
						<p id="store-description"><%= @store.description %></p>

						<% if current_user.stores_id==@store.id %>
							<div class="col-md-2 right-align-card">
								<%= link_to 'Edit', edit_store_path, {:id => 'edit-link'} %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>

		<% if current_user.stores_id==@store.id %>
			<div class="row" style="margin-top:5%;">
				<div class="col-md-12 mx-auto">
					<%= link_to store_path(@store), {:id => 'button-link'} do %>
						<div class="store-button">
							<p> Manage Store </p>
						</div>
					<% end %>

				</div>
			</div>
		<% end %>
	</div>


	<div class="col-md-8">
    <div class="" id="title-item">

      <p> Your Google Calendar </p>
    </div>

    <div class="row">
      <% @calendar_list.items.each do |calendar| %>
      <div class="col-6">
        <div class="calendar-title">
          <%= calendar.summary %>
        </div>

        <%= form_for(:event, url: new_event_url(calendar.id) ) do |f| %>

          <div class="calendar-div">
            <%= f.text_field :name, class: 'calendar-field', required: true, placeholder: "Your Event Name" %>
          </div>

          <div class="calendar-div">
            <%= f.date_field :date, min: Date.today,  class: 'calendar-field', required: true %>
          </div>

          <%= f.submit 'Add event', class: 'str-submit-btn' %>
        <% end %>
      </div>
      <% end %>
    </div>


  </div>

app/views/stores/edit.html.erb
<% content_for :title, "Update Store - " %>
<div class="container information">
<div class="user-form add-store">
  <p id="page-title">Update Information</p>
  <div class="row">
    <div class="col-md-12 mb-3">
    <%= form_for @stores, url:'/store', method: :patch do |f| %>


        <div class="form-group">

          <% if @stores.avatar? %>
          <%= f.label :avatar, "Store Picture" %>
          <div class="cp-div-pic cp-div-remove">
            <div class="cp-div-picupload">
              <%= image_tag image_url(@stores.avatar.url), :class => "cp-remove-pic cp-picture cp-pic-uploaded", :id => "pic-uploaded" %>
            </div>
            <div class="cp-pic-button">
              <div class="cp-picture_field">
                  <%= f.file_field(:avatar, accept: 'image/png,image/gif,image/jpeg', id: 'cp-picture') %>
              </div>
              <div class="cp-choose-pic">Change Picture</div>
              <div class='clearfix'></div>
            </div>
          </div>


          <% else %>

          <%= f.label :avatar, "Store Picture" %>
                <div class="cp-div-pic cp-div-remove">
                  <div class="cp-div-picupload">
                    <img src='#' id='pic-uploaded' class="cp-pic-uploaded cp-miss-pic">
                  </div>
                  <div class="cp-pic-button">
                    <div class="">
                      <%= f.file_field(:avatar, accept: 'image/png,image/gif,image/jpeg', id: 'cp-picture') %>
                    </div>
                    <div class="cp-choose-pic">Choose your picture</div>
                      <div class='clearfix'></div>
                  </div>
                </div>
          <% end %>

        </div>


        <%= f.label :name, "Store Name" %>
        <%= f.text_field :name, class: 'form-control', required: true %>
            <div class="invalid-feedback">
                Invalid Input
            </div>


        <%= f.label :description, "Store Description" %>
        <%= f.text_area :description, :rows => 10, style: 'width:100%;', class: 'form-control', required: true %>
            <div class="invalid-feedback">
                Invalid Input
            </div>

        <br />
        <%= f.submit "Update", class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>
</div>

app/views/stores/events.html.erb
<ul>
  <% @event_list.items.each do |event| %>
    <li><%= event.summary %> (<%= event.id %>)</li>
  <% end %>
</ul>

app/views/stores/history.html.erb
<% content_for :title, "Transaction History - " %>

<div class="row" style="margin-top:5%;">
  <div class="col-md-3">
    <div class="row">
      <div class="col-md-12" id="seller-card">
        <div id="st-info">
          Seller Information
        </div>

        <div id="st-storeinfo">
          <% if @store.avatar? %>
          <%= image_tag(@store.avatar.url, :class => "profile-picture") %>
          <% else %>
          <%= image_tag( "products/p-camera.png", id: 'seller-card-picture') %>
          <% end %>
          <div id="store-information">
            <p id="store-name"><%= @store.name.upcase %></p>
            <p id="store-description"><%= @store.description %></p>

            <% if current_user.stores_id==@store.id %>
              <div class="col-md-2 right-align-card">
                <%= link_to 'Edit', edit_store_path, {:id => 'edit-link'} %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%= link_to store_path(current_user.stores_id), {:id => 'button-link'} do %>
    <div class="row" style="margin-top:5%;">
      <div class="col-md-12 mx-auto">
        <div class="store-button">
          <p> Manage Store </p>
        </div>
      </div>
    </div>
    <% end %>



  </div>


  <div class="col-md-8">
    <div class="row">
      <div class="col-md-8" id="title-item">
        <p> Transaction History </p>

      </div>
    </div>

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([

          ['Task', 'Hours per Day'],
          <% for i in 0..(@month.count-2) %>
          ['<%= @monthDict[i+1] %>', <%= @month[i].count.to_i %>],
          <% end %>
        ]);

        var options = {
          title: 'Transaction Summary Per Month'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>

    <div id="piechart" style="width: 100%; height: 350px;"></div>

    <div class="row">
      <div class="col-md-12">
        <script type="text/javascript">
          google.charts.load('current', {'packages':['table']});
          google.charts.setOnLoadCallback(drawTable);

          var cssClassNames = {
            'headerRow': 'cssHeaderRow',
            'tableRow': 'cssTableRow',
            'oddTableRow': 'cssOddTableRow',
            'selectedTableRow': 'cssSelectedTableRow',
            'hoverTableRow': 'cssHoverTableRow',
            'headerCell': 'cssHeaderCell',
            'tableCell': 'cssTableCell',
            'rowNumberCell': 'cssRowNumberCell'
          };

          function drawTable() {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Order Id');
            data.addColumn('string', 'Item Name');
            data.addColumn('string', 'Quantity');
            data.addColumn('string', 'Buyer');
            data.addColumn('string', 'Status');
            data.addColumn('string', 'Action');
            data.addRows([
              <% @transaction.each do |item| %>
              [ '<%= item.order_id %>', '<%= item.title %>', '<%= item.quantity.to_i %>', '<%= item.buyer %>', '<%= item.status %>',
              '<% if item.status=="Paid" %><%= link_to "Action", store_history_execute_path(:order_id => item.order_id, :product => item.products_id), method: :post %><% else %>Done<% end %>' ],
              <% end %>
            ]);

            var table = new google.visualization.Table(document.getElementById('table_div'));

            table.draw(data, {width: '100%', height: '100%', 'allowHtml': true, 'cssClassNames': cssClassNames});
          }
        </script>

        <div id="table_div"></div>

      </div>
    </div>



  </div>
</div>

app/views/stores/new.html.erb
<% content_for :title, "Create Store - " %>
<div class="container information">
<div class="user-form add-store">
  <p id="page-title">Add a new store</p>
  <div class="row">
    <div class="col-md-12 mb-3">
        <% if current_user.stores_id? %>
            <h4> You already have a store! </h4>
        <% else %>
            <%= form_for(:stores, as: :stores_name, url: stores_path) do |f| %>
                <div class="form-group">
                  <%= f.label :avatar, "Store Picture" %>
                  <br />
                </div>

                <div class="cp-div-pic cp-div-remove">
                  <div class="cp-div-picupload">
                    <img src='#' id='pic-uploaded' class="cp-pic-uploaded cp-miss-pic">
                  </div>
                  <div class="cp-pic-button">
                    <div class="">
                        <%= f.file_field(:avatar, accept: 'image/png,image/gif,image/jpeg', id: 'cp-picture') %>
                    </div>
                    <div class="cp-choose-pic">Choose your picture</div>
                      <div class='clearfix'></div>
                  </div>
                </div>

                <br />

                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.label :name, "Store Name" %>
                <%= f.text_field :name, class: 'form-control', required: true %>
                    <div class="invalid-feedback">
                        Invalid Input
                    </div>

                <br />

                <%= f.label :description, "Store Description" %>
                <%= f.text_area :description, class: 'form-control', required: true %>
                    <div class="invalid-feedback">
                        Invalid Input
                    </div>

                <br />

                  <%= f.submit "Add store", class: 'btn btn-primary' %>

            <% end %>
        <% end %>
    </div>
  </div>
</div>
</div>

app/views/stores/show.html.erb
<% content_for :title, "Store - " %>
<% content_for :head do %>
<%= javascript_include_tag('loader.js') %>
<% end %>
<div class="row" style="margin-top:5%;">
	<div class="col-md-3">
		<div class="row">
			<div class="col-md-12" id="seller-card">
				<div id="st-info">
					Seller Information
				</div>


				<div id="st-storeinfo">
					<% if @store.avatar? %>
				      <%= image_tag(@store.avatar.url, :class => "profile-picture") %>
				    <% else %>
					<%= image_tag( "products/p-camera.png", id: 'seller-card-picture', alt: 'store picture', style: "display: inline;", class: "img-frame") %>
				    <% end %>
					<div id="store-information">
						<p id="store-name"><%= @store.name.upcase %></p>
						<p id="store-description"><%= @store.description %></p>

						<% if  user_signed_in? and current_user.stores_id==@store.id %>
							<div class="col-md-2 right-align-card">
								<%= link_to 'Edit', edit_store_path, {:id => 'edit-link'} %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>

		<% if user_signed_in? and current_user.stores_id==@store.id %>
			<div class="row" style="margin-top:5%;">
				<div class="col-md-12 mx-auto">
					<%= link_to new_product_path, {:id => 'button-link'} do %>
						<div class="store-button">
							<p> Add a New Product </p>
						</div>
					<% end %>

					<%= link_to store_history_path, {:id => 'button-link'} do %>
						<div class="store-button">
							<p> Transaction History </p>
						</div>
					<% end %>

					<% if @check %>

					<%= link_to calendars_path(@store), {:id => 'button-link'} do %>
						<div class="store-button">
							<p> See Calendars </p>
						</div>
					<% end %>

					<% else %>
					<%= link_to redirect_path, {:id => 'button-link'} do %>
						<div class="store-button">
							<p> Link your Calendars </p>
						</div>
					<% end %>

					<% end %>

				</div>
			</div>
		<% end %>
	</div>


	<div class="col-md-8">
		<div id="piechart" style="width: 100%; height: 350px;"></div>

		<div class="row">
			<div class="col-md-8" id="title-item">

				<p> Store Products </p>
			</div>
		</div>

		<div class="row" style="margin-bottom: 5%">
			<div class="col-md-12">

				<% @store_products.each_slice(4) do |group_product| %>
					<div class="row">
						<% group_product.each do |each_product| %>

								<div class="col-6 col-sm-3" id="s-cat-card">
									<%= link_to product_path(each_product), {:id => 's-cat-product-card'} do %>
									<div id="s-cat-div-image">
										<% pic = [] %>

										<% for picture in each_product.pictures %>
								          <% pic << picture %>
								        <% end %>

								        <% if pic === [] %>
								          <%= image_tag( "products/p-camera.png", id: 's-cat-front-image') %>
								        <% else %>
								          <%= image_tag( each_product.pictures[0].image.url, id: 's-cat-front-image') %>
								        <% end %>
									</div>

									<div id="s-cat-desc">
										<p class="s-cat-desc-title"><%= each_product.title %></p>
										<p class="s-cat-desc-price">$ <%= each_product.price %> </p>
									</div>
									<% end %>
								</div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>


		<% if user_signed_in? and current_user.stores_id==@store.id %>

			<% if @store_inactive.exists? %>
				<hr />

				<div class="row">
					<div class="col-md-8" id="title-item">
						<p> Inactive Products </p>
					</div>
				</div>

				<div class="row" style="margin-bottom: 5%">
					<div class="col-md-12">

						<% @store_inactive.each_slice(4) do |group_product| %>
							<div class="row">
								<% group_product.each do |each_product| %>

										<div class="col-6 col-sm-3" id="s-cat-card">
											<%= link_to product_path(each_product), {:id => 's-cat-product-card'} do %>
											<div id="s-cat-div-image">
												<% pic = [] %>
												<% for picture in each_product.pictures %>
										          <% pic << picture %>
										        <% end %>

										        <% if pic === [] %>
										          <%= image_tag( "products/p-camera.png", id: 's-cat-front-image') %>
										        <% else %>
										          <%= image_tag( each_product.pictures[0].image.url, id: 'cat-front-image') %>
										        <% end %>
											</div>

											<div id="s-cat-desc">
												<p class="s-cat-desc-title"><%= each_product.title %></p>
												<p class="s-cat-desc-price">$ <%= each_product.price %> </p>
											</div>
											<% end %>
										</div>
								<% end %>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>

		<% end %>


	</div>
</div>
<script type="text/javascript">
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawChart);
 function drawChart() {
	 var data = google.visualization.arrayToDataTable([
		 ['Task', 'Hours per Day'],
		 <% for category in @categoryDict %>
		 ['<%= category[0] %>', <%= category[1].to_i %> ],
		 <% end %>
	 ]);

	 var options = {
		 title: 'Products Summary based on category'
	 };

	 var chart = new google.visualization.PieChart(document.getElementById('piechart'));

	 chart.draw(data, options);
 }
</script>