config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get '/maps', to: 'maps#index'

  resource :products

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :products do
    resources :pictures
  end

  get :search, controller: :pages


get '/catalogue', to: 'products#index'
get '/category/:id', to: 'products#showcategory', as: :category
get '/carts/checkout', to: 'carts#checkout'
resources :users, only: [:show]
resources :stores, only: [:create, :new, :show]
resource :store, only: [:edit, :update]
resource :cart, only: [:show]
resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
get '/products/:id/deactivate', to: 'products#deactivate'
get '/products/:id/activate', to: 'products#activate'
get '/transactions/checkout', to: 'transaction#checkout'
get '/transactions/execute', to: 'transaction#finish'
get '/user/receipt', to: 'users#receipt'
get '/store/history', to: 'stores#history'
get '/user/history', to: 'users#history'
post '/store/history/execute', to: 'stores#execute'
post '/user/history/execute', to: 'users#execute'

get '/redirect', to: 'stores#redirect', as: 'redirect'
get '/calendarcallback', to: 'stores#callback', as: 'callback'
get '/stores/:id/calendars', to: 'stores#calendars', as: 'calendars'
get '/events/:calendar_id', to: 'stores#events', as: 'events', calendar_id: /[^\/]+/
post '/events/:calendar_id', to: 'stores#new_event', as: 'new_event', calendar_id: /[^\/]+/
get '/user/delete', to: 'users#delete'

  match "404", :to => "pages#not_found", :via => :all
  match "500", :to => "pages#internal_server_error", :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :Products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update

  def subtotal
  	order_items.collect {|items| items.valid? ? (items.quantity * items.unit_price) : 0 }.sum
  end

  private
  def set_order_status
  	self.order_status_id = 1
  end

  def update
  	self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :order_exist
  validate :product_exist

  before_save :update_all

  def unit_price
  	product.price
  end


  private
  def product_exist
  	if product.nil?
  		errors.add(:product,"is not valid")
  	end
  end

  def order_exist
  	if order.nil?
  		errors.add(:order, "is not valid")
  	end
  end

  def update_all
  	self[:unit_price] = unit_price
  	self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :order_items
  has_many :categories, through: :product_categories
  has_many :pictures, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  
  validates :title, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable

	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @items = current_order.order_items
    @user = User.find(current_user.id)

	if @user.address1 != nil && @user.address1 != ""
		@flag = true
	else
		@flag = false
	end
  end

  def checkout
  	@items = current_order.order_items
  	@items.update
  	render root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def header(text)
	  content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<p id="page-title">Your Cart</p>

<% if !@order_item.nil? && @order_item.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% @items.errors.full_messages each do |error_message| %>
			<li> <%= error_message %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

<% if @items.size == 0 %>
	<p class="cart-information">
		There are no items in your Cart. Please <%= link_to "add some items", catalogue_path %> to your cart.
  	</p>

<% else %>
	<% @items.size %>
	<% @items.each do |item| %>
		<%= render 'carts/cart_row', product: item.product, item: item, show_total: true %>
	<% end %>
	<p class="text-right cart-total-price"> Total Price	: <%= number_to_currency current_order.subtotal %> </p>

	<% if @flag %>
		<%= link_to transactions_checkout_url do %>
		<div class="checkout-button">
			Checkout
		</div>
		<% end %>
	<% else %>
			<p> Please update your personal information
				<%= link_to 'first'.html_safe, edit_user_registration_path %> </p>
	<% end %>
<% end %>

app/views/carts/_cart_row.html.erb
<div class="well item-row">

	<div class="row carts-row ">
		<div class="col-md-2 col-6">
			<% unless product.pictures[0].nil? %>
      	<%= image_tag( product.pictures[0].image.url, id: 'pd-image', class: 'pd-image cart-image') %>
			<% end %>
     </div>
		<div class="col-md-4 col-6">
			<p class="cart_product_name"><%= product.title %></p>

			<p> Price: <span style="color: green"><%= number_to_currency item.unit_price %></span></p>
		</div>

		<div class="col-md-6">

			<%= form_for item, remote: true do |f| %>

				<div class="row" style="margin-top:2%;">

					<div class="col-md-4 col-4">
						<%= f.number_field :quantity, value: item.quantity.to_i, class: "form-control cart-price", min: 1 %>
						<%= f.hidden_field :product_id, value: product.id %>
					</div>

					<div class="col-4 text-right">
						<div class="btn-group">
							<%= f.submit "Update", class: "btn cart-update" %>
							<%= link_to "Delete", item, { data: { confirm: "Delete '#{item.product.title}' from your cart?" }, method: :delete, class: "btn cart-delete" } %>
						</div>

					</div>

					<div class="col-4">
						<p class="cart_total text-center"><%= number_to_currency item.total_price %></p>
					</div>

				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/carts/show.html.erb
<% content_for :title, "Cart - " %>
<div class="cart-item">
	<%= render "cart" %>
</div>