config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get '/maps', to: 'maps#index'

  resource :products

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :products do
    resources :pictures
  end

  get :search, controller: :pages


get '/catalogue', to: 'products#index'
get '/category/:id', to: 'products#showcategory', as: :category
get '/carts/checkout', to: 'carts#checkout'
resources :users, only: [:show]
resources :stores, only: [:create, :new, :show]
resource :store, only: [:edit, :update]
resource :cart, only: [:show]
resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
get '/products/:id/deactivate', to: 'products#deactivate'
get '/products/:id/activate', to: 'products#activate'
get '/transactions/checkout', to: 'transaction#checkout'
get '/transactions/execute', to: 'transaction#finish'
get '/user/receipt', to: 'users#receipt'
get '/store/history', to: 'stores#history'
get '/user/history', to: 'users#history'
post '/store/history/execute', to: 'stores#execute'
post '/user/history/execute', to: 'users#execute'

get '/redirect', to: 'stores#redirect', as: 'redirect'
get '/calendarcallback', to: 'stores#callback', as: 'callback'
get '/stores/:id/calendars', to: 'stores#calendars', as: 'calendars'
get '/events/:calendar_id', to: 'stores#events', as: 'events', calendar_id: /[^\/]+/
post '/events/:calendar_id', to: 'stores#new_event', as: 'new_event', calendar_id: /[^\/]+/
get '/user/delete', to: 'users#delete'

  match "404", :to => "pages#not_found", :via => :all
  match "500", :to => "pages#internal_server_error", :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :Products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update

  def subtotal
  	order_items.collect {|items| items.valid? ? (items.quantity * items.unit_price) : 0 }.sum
  end

  private
  def set_order_status
  	self.order_status_id = 1
  end

  def update
  	self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :order_exist
  validate :product_exist

  before_save :update_all

  def unit_price
  	product.price
  end


  private
  def product_exist
  	if product.nil?
  		errors.add(:product,"is not valid")
  	end
  end

  def order_exist
  	if order.nil?
  		errors.add(:order, "is not valid")
  	end
  end

  def update_all
  	self[:unit_price] = unit_price
  	self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :order_items
  has_many :categories, through: :product_categories
  has_many :pictures, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  
  validates :title, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable

	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @status = ''
    @store = Store.all
    if params[:term]
      @product = Product.active.where('title LIKE ?', "%#{params[:term]}%")
      @status = params[:term]
    else
      @product = Product.active.all
    end
    if params[:sort]
      if Product.column_names.include?(params[:sort])
        @product = @product.order(params[:sort])
        @sort_name = params[:sort]
      end
    end
    @sort_url = request.original_url
    if @sort_url[-9..-1] == 'catalogue'
      @sort_url = request.original_url+'?'
    elsif @sort_url.include? "availability"
      @sort_url.slice! "&sort=availability"
    elsif @sort_url.include? "price"
      @sort_url.slice! "&sort=price"
    elsif @sort_url.include? "title"
      @sort_url.slice! "&sort=title"
    end

    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
    3.times { @product.pictures.build }
    @category = Category.all
  end

  def create
    @product = Product.new(product_param)
    if @product.save
      @product.update_column(:active, true)
      redirect_to @product, :notice => "Successfully created product."
    else
      render :action => 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
    @store = Store.find(@product.stores_id)
    @order_item = current_order.order_items.new
    @pictureslink = []
    for picture in @product.pictures
      @pictureslink << picture.image.url
    end
  end

  def edit
    @product = Product.find(params[:id])
    @category = Category.all
    pic = []
    for picture in @product.pictures
      pic << picture
    end

    iteration = 3-pic.count
    i = 0
    while i < iteration
      @product.pictures.build
      i+=1
    end
  end

  def update
    @product = Product.find(params[:id])
    puts @product.price.to_i
    if @product.update(product_param)
      redirect_to @product, :notice  => "Successfully updated product."
    else
      Rails.logger.info(@product.price)
      Rails.logger.info(@product.errors.messages.inspect)
      render :action => 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to "/catalogue", :notice => "Successfully destroyed product."
  end

  def showcategory
    @category = Category.find(params[:id])
    @product = Product.active
    @store = Store.all
    @prod_cat = []
    for product in @product
      if product["categories_id"].to_s == params[:id].to_s
        @prod_cat << product
      end
    end
  end

  def deactivate
    @product = Product.find(params[:id])
    @product.update_column(:active, false)
    redirect_to product_url(@product.id)
  end

  def activate
    @product = Product.find(params[:id])
    @product.update_column(:active, true)
    redirect_to product_url(@product.id)
  end

  private

  def product_param
    params.require(:product).permit(:title, :description, :availability, :price, :maps, :categories_id, :stores_id, pictures_attributes: [:product_id, :id, :image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def header(text)
	  content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/edit.html.erb
<% content_for :title, "Update Product - " %>
<style>
/* Always set the map height explicitly to define the size of the div
* element that contains the map. */
#map {
 height: 50vh;
}
</style>
<div>
  <p id="page-title">Edit Product</p>
  <br/>
  <%= form_for @product, :html => { :multipart => true } do |f| %>
  <div class="row cp-form-row">
    <div class="col-sm-3 cp-form-name">Poduct Name </div>
    <div class="col-sm-9"><%= f.text_field :title, class: 'cp-text-field'%></div>
  </div>

  <div class="row cp-form-row">
    <div class="col-sm-3 cp-form-name">Product Category </div>
    <div class="col-sm-9">
      <%= f.collection_select(:categories_id, Category.all, :id, :title, {}, class: "custom-select") %>
    </div>
  </div>
  <div class="row cp-form-row">
    <div class="col-sm-3 cp-form-name">Poduct Picture </div>
    <div class="col-sm-9">
      <div class="row">

        <%= f.fields_for :pictures, @product.picture do |picture_field| %>
          <% if picture_field.object.new_record? %>
          <div class="col-md-4 cp-div-pic cp-div-remove">
            <div class="cp-div-picupload">
              <img src='#' id='pic-uploaded' class="cp-pic-uploaded cp-miss-pic">
            </div>
            <div class="cp-pic-button">
              <div class="">
                <%= picture_field.file_field(:image, accept: 'image/png,image/gif,image/jpeg', id: 'cp-picture') %>
              </div>
              <div class="cp-choose-pic">Choose your picture</div>
  	          <div class='clearfix'></div>
            </div>
          </div>

          <% else %>
          <div class="col-md-4 cp-div-pic cp-div-remove">
            <div class="cp-div-picupload">
              <%= link_to image_tag(picture_field.object.image.url), :class => "cp-remove-pic" %>
            </div>
            <div class="cp-pic-button">
              <div class="cp-picture_field">
                <%= picture_field.file_field(:image, accept: 'image/png,image/gif,image/jpeg', id: 'cp-picture') %>
              </div>
              <div class="cp-choose-pic">Change</div>
              <div class='clearfix'></div>
            </div>
          </div>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>

  <div class="row cp-form-row">
    <div class="col-sm-3 cp-form-name">Price </div>
    <div class="col-sm-3"><%= f.number_field :price, class: 'cp-text-field', required: true, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any, min: 0 %></div>
      <%= f.hidden_field :availability, value:'1' %>
  </div>

  <div class="row cp-form-row">
    <div class="col-sm-3 cp-form-name">Description </div>
    <div class="col-sm-9"><%= f.text_area :description, class: 'cp-text-field' %></div>
  </div>

  <div class="col-sm-3 cp-form-name">Location</div>
  <%= f.hidden_field :maps, id:'geoloc' %>
  <!-- <%= f.text_field :maps, class: 'controls', id:'pac-input', placeholder:'Search box' %> -->
  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="map"></div>

  <%= f.submit :class => 'cp-submit' %>

  <% end %>

</div>

<script>
// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

// This example requires the Places library. Include the libraries=places
// parameter when you first load the API. For example:
// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

function initAutocomplete() {
  var geoloc = document.getElementById('geoloc');
  console.log(geoloc.value);
  var geoloc = geoloc.value.split(",");
  if (isNaN(parseFloat(geoloc[0]))) {
    var currentloc = {lat: -25.274398, lng: 133.77513599999997};
    var zoomnumber = 5;
  }
  else {
    var currentloc = {lat: parseFloat(geoloc[0]), lng: parseFloat(geoloc[1])};
    var zoomnumber = 16;
  }
  var map = new google.maps.Map(document.getElementById('map'), {
    center: currentloc,
    zoom: zoomnumber,
    mapTypeId: 'roadmap'
  });

  if (currentloc['lat'] != -25.274398 && currentloc['lng'] != 133.77513599999997){
    var marker = new google.maps.Marker({
      position: currentloc,
      map: map,
      label: 'Current product location'
    });
  }

  // Create the search box and link it to the UI element.
  var input = document.getElementById('pac-input');
  var searchBox = new google.maps.places.SearchBox(input);
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

  // Bias the SearchBox results towards current map's viewport.
  map.addListener('bounds_changed', function() {
    searchBox.setBounds(map.getBounds());
  });

  var markers = [];
  // Listen for the event fired when the user selects a prediction and retrieve
  // more details for that place.
  searchBox.addListener('places_changed', function() {
    var places = searchBox.getPlaces();

    if (places.length == 0) {
      return;
    }

    // Clear out the old markers.
    markers.forEach(function(marker) {
      marker.setMap(null);
    });
    markers = [];

    // For each place, get the icon, name and location.
    var bounds = new google.maps.LatLngBounds();
    places.forEach(function(place) {
      if (!place.geometry) {
        console.log("Returned place contains no geometry");
        return;
      }
      var icon = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };

      // Create a marker for each place.
      markers.push(new google.maps.Marker({
        map: map,
        icon: icon,
        title: place.name,
        position: place.geometry.location
      }));

      var geoloc = document.getElementById('geoloc');
      var latlang = place.geometry.location.lat() + ',' + place.geometry.location.lng();
      geoloc.value = latlang;

      if (place.geometry.viewport) {
        // Only geocodes have viewport.
        bounds.union(place.geometry.viewport);
      } else {
        bounds.extend(place.geometry.location);
      }
    });
    map.fitBounds(bounds);
  });

}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["MAPS_API"] %>&callback=initAutocomplete&libraries=places" async defer></script>

app/views/products/index.html.erb
<% content_for :title, "Catalogue - " %>
<div id="small-page">

	<% if @status == '' %>
	<p id="page-title">Catalogue</p>
	<% else %>
	<p id="page-title">Search for '<%= @status %> '</p>
	<% end %>

	<div class="" style="width:40%;">
		<% if user_signed_in? and current_user.stores_id? %>
			<%= link_to new_product_path, {:id => 'p-button-link'} do %>
				<div class="store-button">
					<p> Add a New Product </p>
				</div>
			<% end %>
		<% end %>
	</div>

	<% if @product.count > 0 %>
	<!-- if there are products -->
		<div class="dropdown sort-dropdown">
			<button class="btn btn-default dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				Sort by <%= @sort_name %>
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu sort-dropdown-menu" aria-labelledby="sortDropdown">
				<a href="<%= @sort_url+"&sort=title" %>" data-value="title" class="dropdown-item">Sort by Title</a>
				<a href="<%= @sort_url+"&sort=price" %>" data-value="price" class="dropdown-item">Sort by Price</a>
				<a href="<%= @sort_url+"&sort=availability" %>" data-value="sort by availability" class="dropdown-item">Sort by Availability</a>
			</ul>
		</div>

		<% @product.each_slice(4) do |group_product| %>
		<div class="row">
			<% group_product.each do |each_product| %>
					<div class="col-6 col-sm-3" id="cat-card">
						<%= link_to product_path(each_product), {:id => 'cat-product-card'} do %>
						<div id="cat-div-image">
							<% pic = [] %>
							<% for picture in each_product.pictures %>
					          <% pic << picture %>
					        <% end %>
					        <% if pic === [] %>
					          <%= image_tag( "products/p-camera.png", id: 'cat-front-image') %>
					        <% else %>
					          <%= image_tag( each_product.pictures[0].image.url, id: 'cat-front-image') %>
					        <% end %>
						</div>

						<div id="cat-desc">
							<p class="cat-desc-title"><%= each_product.title %></p>
							<p class="cat-desc-price">$ <%= each_product.price %> </p>
							<br/><p class="h-cat-desc-store"><%= @store.find(each_product.stores_id).name %></p>
						</div>
						<% end %>
					</div>

			<% end %>
		</div>
		<% end %>


	<!-- if there is no product -->
	<% else %>
	<div class="no-product-txt">
		Sorry :( There is no product
		<br/>Go back to <%= link_to root_path do%> home <% end %>
	</div>

	<% end %>
</div>

app/views/products/show.html.erb
<% content_for :title, "Product - " %>
<% content_for :head do %>
<!-- CamanJs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/camanjs/4.1.2/caman.full.min.js"></script>
<% end %>
<style>
/* Always set the map height explicitly to define the size of the div
* element that contains the map. */
#map {
 height: 50vh;
}
</style>
<div class="error-text">
</div>

<div id="small-page">

  <p style="margin-top:5%;"> </p>
  <% pic = [] %>
  <div class="row">
    <div class="col-sm-4">
      <div class="pd-div-image">
        <% for picture in @product.pictures %>
          <% pic << picture %>
        <% end %>

        <% if pic === [] %>
          <%= image_tag( "products/p-camera.png", id: 'pd-clicked-image', class: 'pd-clicked-image') %>
        <% else %>
          <%= image_tag( @product.pictures[0].image.url, id: 'pd-clicked-image', class: 'pd-clicked-image', crossorigin:'anonymous') %>
        <% end %>

      </div>

      <div class="row" style="padding: 5%">
        <% for picture in @product.pictures %>
      		<div class="col-4 pd-image-small" id="pd-div-image-small">
            <%= link_to image_tag(picture.image.url, id: 'pd-image') %>
          </div>
      	<% end %>
      </div>
      <% picture = @product.pictures[0] %>
      <% unless picture.nil? %>
      <p style="font-weight:700">Do more with the image!</p>
      Contrast<br/>
      <input type="range" name="contrast" class="custom-range" min="-100" max="100" id="contrast" value="0">
      Brightness<br/>
      <input id="bright" name="bright" class="custom-range" type="range" min="-100" max="100" value="0">
      Saturation<br/>
      <input id="satr" name="satr" class="custom-range" type="range" min="-100" max="100" value="0">
      Exposure<br/>
      <input id="expos" name="expos" class="custom-range" type="range" min="-100" max="100" value="0">

      <button id="resetbtn" class="btn btn-for-caman">Reset Photo</button>
      <% end %>
    </div>

    <div class="col-sm-5">
      <% if user_signed_in? and current_user.stores_id==@product.stores_id %>
        <p>
          <div class="row">
            <div class="col-6">
              <%= link_to edit_product_path(@product), {:id => 'p-button-link'} do %>
    						<div class="product-button">
    							<p> Edit Product </p>
    						</div>
    					<% end %>
            </div>
            <div class="col-6">
              <% if @product.active == true %>
                <div class="de-ac">
                  <%= link_to controller: "products", action: "deactivate", id: @product do %>
                  <div class="product-button">
      							<p> Deactivate </p>
      						</div>
                  <% end %>
                </div>
              <% else %>
                <div class="de-ac">
                  <%= link_to controller: "products", action: "activate", id: @product do %>
                  <div class="product-button">
      							<p> Activate </p>
      						</div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </p>
      <% end %>

      <p id="page-title"><%= @product.title %></p>
      <p>
        <%= @product.description %>
      </p>

      <div id="map"></div>
    </div>


    <% unless user_signed_in? and current_user.stores_id==@product.stores_id %>
      <div class="col-sm-3">
        <%= form_for @order_item, remote: true do |f| %>
        <div id="pd-div-price">
          <div class="pd-price-txt">$ <%= @product.price %></div>
          Quantity: <%= f.number_field :quantity, value: 1, class: "form-control quantity-form", min: 1 %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :order_status_id, value: 1 %>
        </div>

        <div id="pd-div-addtocart">
            <% if user_signed_in? %>
              <%= f.submit "ADD TO CART", class: 'btn btn-outline-primary cart-button'%>
            <% else %>
              <a href="/users/sign_up"><input name="commit" value="REGISTER TO BUY" class="btn btn-outline-primary cart-button" data-disable-with="REGISTER"></a>
            <% end %>
          <% end %>
        </div>

        <div id="pd-div-seller">
          seller information
        </div>

        <%= link_to store_path(@product.stores_id), id: 'seller-info-button' do %>
        <div id="pd-div-sellerinfo">
          <% if @store.avatar? %>
              <%= image_tag(@store.avatar.url, :class => "profile-picture") %>
            <% else %>
          <%= image_tag( "products/p-camera.png", id: 'seller-card-picture', alt: 'store picture', style: "display: inline;", class: "img-frame") %>
          <% end %>

          <div id="store-information">
            <p id="store-name"><%= @store.name.upcase %></p>
            <p id="store-description"><%= @store.description %></p>
            <br/>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script>
// This example adds a search box to a map, using the Google Place Autocomplete
// feature. People can enter geographical searches. The search box will return a
// pick list containing a mix of places and predicted search terms.

// This example requires the Places library. Include the libraries=places
// parameter when you first load the API. For example:
// <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

function initAutocomplete() {
  var geoloc = '<%= @product.maps %>'
  var geoloc = geoloc.split(",");
  if (isNaN(parseFloat(geoloc[0]))) {
    var currentloc = {lat: -25.274398, lng: 133.77513599999997};
    var zoomnumber = 5;
  }
  else {
    var currentloc = {lat: parseFloat(geoloc[0]), lng: parseFloat(geoloc[1])};
    var zoomnumber = 16;
  }
  var map = new google.maps.Map(document.getElementById('map'), {
    center: currentloc,
    zoom: zoomnumber,
    mapTypeId: 'roadmap'
  });

  if (currentloc['lat'] != -25.274398 && currentloc['lng'] != 133.77513599999997){
    var marker = new google.maps.Marker({
      position: currentloc,
      map: map,
      label: 'Product location'
    });
  }

}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["MAPS_API"] %>&callback=initAutocomplete&libraries=places" async defer></script>

app/views/products/showcategory.html.erb
<% content_for :title, "Category - " %>
<div id="small-page">
	<p id="page-title">Category "<%= @category["title"] %>"</p>

	<% if @prod_cat.count > 0 %>

	<% @prod_cat.each_slice(4) do |group_product| %>
	<div class="row">
		<% group_product.each do |each_product| %>

				<div class="col-6 col-sm-3" id="cat-card">
					<%= link_to product_path(each_product), {:id => 'cat-product-card'} do %>
					<div id="cat-div-image">
						<% pic = [] %>
						<% for picture in each_product.pictures %>
		          <% pic << picture %>
		        <% end %>

		        <% if pic === [] %>
		          <%= image_tag( "products/p-camera.png", id: 'cat-front-image') %>
		        <% else %>
		          <%= image_tag( each_product.pictures[0].image.url, id: 'cat-front-image') %>
		        <% end %>
					</div>
					<div id="cat-desc">
						<p class="cat-desc-title"><%= each_product.title %></p>
						<p class="cat-desc-price">$ <%= each_product.price %> </p>
						<br/><p class="h-cat-desc-store"><%= @store.find(each_product.stores_id).name %></p>
					</div>
					<% end %>
				</div>

		<% end %>
	</div>
	<% end %>

	<% else %>

	<div class="no-product-txt">
		Sorry :( There is no product
		<br/>Go back to <%= link_to root_path do%> home <% end %>
	</div>

	<% end %>

</div>