config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get '/maps', to: 'maps#index'

  resource :products

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  resources :products do
    resources :pictures
  end

  get :search, controller: :pages


get '/catalogue', to: 'products#index'
get '/category/:id', to: 'products#showcategory', as: :category
get '/carts/checkout', to: 'carts#checkout'
resources :users, only: [:show]
resources :stores, only: [:create, :new, :show]
resource :store, only: [:edit, :update]
resource :cart, only: [:show]
resources :order_items, only: [:create, :update, :destroy], defaults: { format: 'js' }
get '/products/:id/deactivate', to: 'products#deactivate'
get '/products/:id/activate', to: 'products#activate'
get '/transactions/checkout', to: 'transaction#checkout'
get '/transactions/execute', to: 'transaction#finish'
get '/user/receipt', to: 'users#receipt'
get '/store/history', to: 'stores#history'
get '/user/history', to: 'users#history'
post '/store/history/execute', to: 'stores#execute'
post '/user/history/execute', to: 'users#execute'

get '/redirect', to: 'stores#redirect', as: 'redirect'
get '/calendarcallback', to: 'stores#callback', as: 'callback'
get '/stores/:id/calendars', to: 'stores#calendars', as: 'calendars'
get '/events/:calendar_id', to: 'stores#events', as: 'events', calendar_id: /[^\/]+/
post '/events/:calendar_id', to: 'stores#new_event', as: 'new_event', calendar_id: /[^\/]+/
get '/user/delete', to: 'users#delete'

  match "404", :to => "pages#not_found", :via => :all
  match "500", :to => "pages#internal_server_error", :via => :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :Products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update

  def subtotal
  	order_items.collect {|items| items.valid? ? (items.quantity * items.unit_price) : 0 }.sum
  end

  private
  def set_order_status
  	self.order_status_id = 1
  end

  def update
  	self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :order_exist
  validate :product_exist

  before_save :update_all

  def unit_price
  	product.price
  end


  private
  def product_exist
  	if product.nil?
  		errors.add(:product,"is not valid")
  	end
  end

  def order_exist
  	if order.nil?
  		errors.add(:order, "is not valid")
  	end
  end

  def update_all
  	self[:unit_price] = unit_price
  	self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :product
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :order_items
  has_many :categories, through: :product_categories
  has_many :pictures, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  
  validates :title, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable

	  has_attached_file :avatar

	  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  	def send_devise_notification(notification, *args)
	  devise_mailer.send(notification, self, *args).deliver_later
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def header(text)
	  content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart_text.html.erb
<div style="padding-right:3%;" class="cart-text">
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> Go Market</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Logo on tab -->
    <%= favicon_link_tag 'logo-05.png' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= javascript_include_tag('jquery.easy-autocomplete.js') %>

    <%= yield :head %>

    <!-- autocomplete -->

  </head>

  <body id="override-bootstrap">
    <div class="body-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">
        <div class="navbar-brand" style="width:27%">
          <%= link_to root_path do%>
            <%= image_tag('logo-04.png', :alt => "logo", :class => "ml-5 navbar-logo") %>
          <% end %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- category button -->
            <div class="btn-group">
              <button type="button" class="nav-btn-allcategory dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="/category/1">Furniture</a>
                <a class="dropdown-item" href="/category/2">Fashion</a>
                <a class="dropdown-item" href="/category/3">Office & Stationary</a>
                <a class="dropdown-item" href="/category/4">Foods & Drinks</a>
                <a class="dropdown-item" href="/category/5">Kitchen Tools</a>
                <a class="dropdown-item" href="/category/6">Tools</a>
                <a class="dropdown-item" href="/category/7">Automative</a>
                <a class="dropdown-item" href="/category/8">Hobby</a>
              </div>
            </div>

          <!--<form class="form-inline my-2 my-lg-0" id="nav-form"> -->
            <!-- search form -->
            <%= form_tag catalogue_path, :class => "form-inline my-2 my-lg-0", :id => "nav-form", method: :get do %>
              <%= text_field_tag :term, params[:term], class: "nav-form-search mr-sm-2", :placeholder => "Search for Products, Brands and more" %>


            <!-- <input class="nav-form-search mr-sm-2 " type="text" placeholder="Search for Products, Brands and more" aria-label="Search"> -->

            <!-- <button class="my-2 my-sm-0 nav-btn-search" type="submit">Search</button> -->
            <%= submit_tag 'Search', class: "my-2 my-sm-0 nav-btn-search" %>
           <% end %>
          <!-- </form>-->

          <% if user_signed_in? %>
            <%= render 'layouts/cart_text' %>
          <% end %>

          <ul class="navbar-nav mr-auto profile">
            <% if user_signed_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.firstName %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Profile', user_path(current_user.id), :class => "dropdown-item" %>

                <% if current_user.stores_id==nil or current_user.stores_id=="" %>
                  <%= link_to 'Create a store', new_store_path, :class => "dropdown-item" %>
                <% else %>
                  <%= link_to 'Manage store', store_path(current_user.stores_id), :class => "dropdown-item" %>
                <% end %>

                <%= link_to 'My Orders', user_history_path, :class => "dropdown-item"  %>


                <div class="dropdown-divider"></div>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => "dropdown-item"  %>
              </div>
            </li>

            <% else %>

            <li class="nav-item" style="margin-right:10px">
              <%= link_to 'Log In', new_user_session_path, {:class => "nav-attribute"} %>
            </li>

            <div class="verticalLine"></div>

            <li class="nav-item btn-sign-up">
              <%= link_to 'Sign Up', new_user_registration_path, {:class => "nav-attribute"} %>
            </li>

            <% end %>

          </ul>
        </div>
      </nav>

      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        <% end %>
      </div>

      <%= yield :top_content %>

      <div class="container">
          <h1><%= yield :header %></h1>
        <%= yield %>
      </div>

    </div>
    <section id="section-footer">
  		<div class="container">
  			<div class="row">
  				<div class="col-md-3">
            <ul>
              <li>Go Market</li>
              <li>About us</li>
              <li>Career</li>
              <li>Blog</li>
              <li>Store</li>
              <li>Our activity</li>
              <li>Contact support</li>
            </ul>
          </div>
          <div class="col-md-3">
            <ul>
              <li>Buy</li>
              <li>Buy at GoMarket</li>
              <li>How to buy</li>
              <li>Checkout</li>
              <li>Refund</li>
              <li>Hot list</li>
            </ul>
          </div>
          <div class="col-md-3">
            <ul>
              <li>Sell</li>
              <li>How to sell</li>
              <li>Gold merchant</li>
              <li>Promotion</li>
              <li>Transfer</li>
            </ul>
          </div>
          <div class="col-md-3">
            <ul class="social-media">
              <li>Don't forget to visit us at</li>
              <li><i class="fab fa-instagram"></i></li>
              <li><i class="fab fa-facebook"></i></li>
              <li><i class="fab fa-twitter"></i></li>
              <li><i class="fab fa-youtube"></i></li>
            </ul>
          </div>
  			</div>
  		</div>
  	</section>

    <!-- Font awesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/login/loginForm.html.erb
<div class="row">
	<div class="col-md-4 mx-auto">
            <form class="needs-validation" novalidate>
            	<div class="row">
            		<div class="col-md-12 mb-3">
            			<div class="form-group">
	            			<label for="inputEmail">Email address</label>
						    <input type="email" class="form-control" id="inputEmail" placeholder="Email" required>
						    <div class="invalid-feedback">
								Please provide a valid email.
      						</div>
						</div>
						<div class="form-group">
							<label for="inputPassword">Password</label>
							<input type="password" class="form-control" id="inputPassword" placeholder="Password" data-error="Password is invalid" required>
						    <div class="invalid-feedback">
								Password is incorrect
      						</div>
						</div>
					</div>
				</div>
				<button class="btn btn-primary" type="submit">Submit form</button>
            </form>
	</div>
</div>


<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/pages/index.html.erb
<% content_for :top_content do %>
<div class="container" style="margin-top:2%;">
  <div id="carouselExampleControls" class="carousel slide carousel-banner" data-ride="carousel">
    <div class="carousel-inner">

      <div class="carousel-item active">
        <%= link_to '/catalogue?utf8=✓&term=sofa&commit=Search' do %>
        <%= image_tag( "homepage/banner-01.png", class: 'd-block w-100') %>
        <% end %>
      </div>

      <div class="carousel-item">
        <%= link_to '/catalogue?utf8=✓&term=milk&commit=Search' do %>
        <%= image_tag( "homepage/banner-02.png", class: 'd-block w-100') %>
        <% end %>
      </div>
      <div class="carousel-item">
        <%= link_to '/catalogue?utf8=✓&term=tote+bag&commit=Search' do %>
        <%= image_tag( "homepage/banner-03.png", class: 'd-block w-100') %>
        <% end %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="h-text-1">
    <div class="main">What items do you want?</div>
    <div class="context">We have thousands of items available. Search in the map below!</div>
  </div>

  <div style="">
    <a href="/maps"><%= image_tag( "homepage/maps-section-04-01.png", class: 'd-block w-100 h-img-map') %></a>
  </div>

  <div class="h-text-cat" style="margin-top:5%">
    <div class="main">Categories</div>

    <div class="row" style="margin-top:2%;">

      <div class="col-lg-3 col-6">
        <div class="row">
          <div class="col-6">
            <a href="/category/1"><div class="cat-border">
              <%= image_tag( "category/category-01.png", class: 'h-why-img') %>
              Furniture
            </div></a>
          </div>

          <div class="col-6">
            <a href="/category/2"><div class="cat-border">
              <%= image_tag( "category/category-02.png", class: 'h-why-img') %>
              Fashion
            </div></a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-6">
        <div class="row">
          <div class="col-6">
            <a href="/category/3"><div class="cat-border">
              <%= image_tag( "category/category-03.png", class: 'h-why-img') %>
              Stationary
            </div></a>
          </div>
          <div class="col-6">
            <a href="/category/4"><div class="cat-border">
              <%= image_tag( "category/category-04.png", class: 'h-why-img') %>
              Foods & Drink
            </div></a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-6">
        <div class="row">
          <div class="col-6">
            <a href="/category/5"><div class="cat-border">
              <%= image_tag( "category/category-05.png", class: 'h-why-img') %>
              Kitchen Tools
            </div></a>
          </div>
          <div class="col-6">
            <a href="/category/6"><div class="cat-border">
              <%= image_tag( "category/category-06.png", class: 'h-why-img') %>
              Tools
            </div></a>
          </div>
        </div>
      </div>

      <div class="col-lg-3 col-6">
        <div class="row">
          <div class="col-6">
            <a href="/category/7"><div class="cat-border">
              <%= image_tag( "category/category-07.png", class: 'h-why-img') %>
              Automative
            </div></a>
          </div>
          <div class="col-6">
            <a href="/category/8"><div class="cat-border">
              <%= image_tag( "category/category-08.png", class: 'h-why-img') %>
              Hobby
            </div></a>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="h-text-c" style="margin-top:5%;">
    <div class="main">Catalogue</div>
    <div class="context">Dozens of catalogues!</div>
    <div class="row" style="margin-top:2%;">
      <div class="col-md-11 col-9">

        <section class="horizontal-scroll">
          <% @product.each do |each_product| %>
          <div class="hc-item">
            <%= link_to product_path(each_product), {:id => 'cat-product-card'} do %>
          	<div id="h-cat-div-image">
            <% pic = [] %>
						<% for picture in each_product.pictures %>
		          <% pic << picture %>
		        <% end %>
		        <% if pic === [] %>
		          <%= image_tag( "products/p-camera.png", id: 'cat-front-image') %>
		        <% else %>
		          <%= image_tag( each_product.pictures[0].image.url, id: 'cat-front-image') %>
		        <% end %>
            </div>
            <div id="h-cat-desc">
    					<p class="h-cat-desc-title"><%= each_product.title %></p>
    					<p class="h-cat-desc-price">$ <%= each_product.price %> </p>
    					<br/><p class="h-cat-desc-store"><%= @store.find(each_product.stores_id).name %> </p>
    					<!-- <p>Toowong, 2 km</p> -->
    				</div>
            <% end %>
          </div>

          <% end %>

        </section>

      </div>

      <div class="col-md-1 col-3 hc-see-more" onclick="window.location.href = '/catalogue'">
        see
        <br/>more
      </div>

    </div>

  </div>

  <% if current_user %>

  <% else %>
  <div class="row" style="margin:10% 0%">
    <div class="col-sm-3">
      <div class="h-text-1">
        <div class="main">You have your own industry?</div>
        <div class="context">Register your home industry here!</div>
          <div class="h-btn-register">
            <%= link_to 'FREE REGISTER', new_user_registration_path, class: 'h-btn-register-text' %>
          </div>
      </div>
    </div>
    <div class="col-sm-3">
      <%= image_tag( "homepage/why-gomarket-06.png", class: 'h-why-img') %>
      <div class="h-text-1" style="text-align:center">
        <div class="main">EASY</div>
        <div class="context"></div>
      </div>
    </div>
    <div class="col-sm-3">
      <%= image_tag( "homepage/why-gomarket-07.png", class: 'h-why-img') %>
      <div class="h-text-1" style="text-align:center">
        <div class="main">PRACTICAL</div>
        <div class="context"></div>
      </div>
    </div>
    <div class="col-sm-3">
      <%= image_tag( "homepage/why-gomarket-08.png", class: 'h-why-img') %>
      <div class="h-text-1" style="text-align:center">
        <div class="main">MORE MARKET</div>
        <div class="context"></div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/pages/internal_server_error.html.erb
<% content_for :title, "500 - " %>
<!-- error 500 -->

<h1 style="font-weight: 700; margin-top: 5%;">
	500 Page:
</h1>

<h3> Wrong Move Champ! </h3>

<p style="margin-top: 5%;">
<%= link_to  "/catalogue" do %>
	<div class="error-button">
		See GoMarket catalogues
	</div>
<% end %>
</p>

app/views/pages/not_found.html.erb
<% content_for :title, "400 - " %>
<h1 style="font-weight: 700; margin-top: 5%;">
	404 Page:
</h1>

<h3> Wrong Move Champ! </h3>

<p style="margin-top: 5%;">
<%= link_to  "/catalogue" do %>
<div class="no-product-txt">
	Sorry :(
	<br/>Go back to <%= link_to root_path do%> home <% end %>
</div>
<% end %>
</p>